Update dependency versions, remove usage of dep, update maxctrl_expor…
Vetal1977/maxctrl_exporter pull request #8
Opened 2021-10-02 16:36 UTC by Vetal1977

- Updated dependency versions
- Removed usage of dep
- Updated maxctrl_exporter version
- Added `Contribution` section into README

2021-10-04 16:34 UTC, pgporada requested changes

2021-10-04 16:34 UTC, pgporada commented on go.mod
>  go 1.15
Bump this go to 1.17

2021-10-05 10:51 UTC, Vetal1977 commented on go.mod
>  go 1.15
@pgporada Updated. Thank you!

2021-10-07 08:16 UTC, ktugan commented
Sorry @Vetal1977 I saw this one too late. I see you pushed already to master. Closing this PR.

2021-10-07 08:16 UTC, closed without merging

2021-10-07 08:17 UTC, ktugan commented
My bad. I see that the force push was on the branch itself :) Reopening.